name: pypgatk_decoy
description: A module for the generation of a decoy peptide database
keywords:
  - peptide
  - protein
  - decoy
  - database
tools:
  - generate_decoy:
      description: takes a protein database and generates a decoy database
      documentation: https://pgatk.readthedocs.io/en/latest/pypgatk.html
      licence: 
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'database' ]
    - database:
        type: file
        description: input database used to build a decoy
        pattern: ".fa"
        ontologies: []
    - decoy_config:
        type: file
        description: config file used to define the paramiters of the process
        pattern: ".yaml"
        ontologies: []
output:
  file_out:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id: 'decoy_proteindb' ]
      - database:
          type: file
          description: output peptide database
          pattern: ".fa"
          ontologies: []
      - versions:
    -     versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
          ontologies:
            - edam: http://edamontology.org/format_3750 # YAML

authors:
  - "@alistairrice"
maintainers:
  - "@hywelldunn-davies"